---
- hosts: all
  vars:
    project_user: jekyll
    jekyll_user: "{{project_user}}"
    rvm_user: "{{jekyll_user}}"
    rvm_ruby_version: 2.1.4
  roles:
    - apt
    - user
    - gpg
    - rvm
  tasks:
    - name: check if jekyll is already install
      command: sudo -iu {{jekyll_user}} bash -c '. ~/.rvm/scripts/rvm; gem list'
      register: jekyll_check_result
      changed_when: False

    - name: install jekyll
      command: sudo -iu {{jekyll_user}} bash -c '. ~/.rvm/scripts/rvm; gem install jekyll'
      when: jekyll_check_result.stdout.find('jekyll') == -1
